version: "3.3"
services:
        nginx:
                build:
                        context: .
                        dockerfile: requirements/nginx/Dockerfile 
                image: nginx
                container_name: nginx_container
                ports:
                        - "443:443"
                volumes:
                        - dbdata:/volumes
                depends_on:
                        - wordpress
                restart: always
        wordpress:
                build:
                        context: .
                        dockerfile: requirements/wordpress/Dockerfile 
                image: wordpress
                container_name: wordpress_container
                ports:
                        - "9000:9000"
                volumes:
                        - dbdata:/volumes
                restart: always
        mariadb:
                build:
                        context: .
                        dockerfile: requirements/mariadb/Dockerfile 
                image: mariadb
                container_name: mariadb_container
                ports:
                        - "3306:3306"
                volumes:
                        - mariadb:/volumes
                restart: always
volumes:
  dbdata:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/nlocusso/data/wordpress/'
  mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/nlocusso/data/mariadb/'
