version: "3.3"
services:
        nginx:
                build: requirements/nginx
                image: nginx
                container_name: nginx_container
                ports:
                        - "443:443"
                volumes:
                        - dbdata:/volumes
                depends_on:
                        - wordpress
                env_file:
                        - .env
                networks:
                        - localhost
                restart: always
        wordpress:
                build: requirements/wordpress
                image: wordpress
                container_name: wordpress_container
                volumes:
                        - dbdata:/volumes
                depends_on:
                        - mariadb
                        - redis
                env_file:
                        - .env
                networks:
                        - localhost
                restart: always
        mariadb:
                build: requirements/mariadb
                image: mariadb
                container_name: mariadb_container
                volumes:
                        - mariadb:/var/lib/mysql
                env_file:
                        - .env
                networks:
                        - localhost
                restart: always
        redis:
                build: requirements/bonus/redis
                image: redis
                container_name: redis_container
                ports:
                        - '6379:6379'
                volumes:
                        - cache:/data
                networks:
                        - localhost
                restart: always

volumes:
  dbdata:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/nlocusso/data/wordpress/'
  mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/nlocusso/data/mariadb/'
  cache:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/nlocusso/data/redis/'

networks:
        localhost:
                driver: bridge
